# Generated by Django 4.2.9 on 2026-02-16 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"verbose_name": "Корзины", "verbose_name_plural": "Корзины"},
        ),
    ]
