# Generated by Django 4.2.7 on 2026-01-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0002_alter_categories_options_alter_categories_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="discount",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=4, verbose_name="Скидка"
            ),
        ),
    ]
