# Generated by Django 4.2.9 on 2026-02-03 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0003_alter_products_discount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="products",
            options={
                "ordering": ("id",),
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
