# Generated by Django 4.2.9 on 2026-02-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0004_alter_products_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="name",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Название Продукта"
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="slug",
            field=models.SlugField(
                blank=True,
                max_length=200,
                null=True,
                unique=True,
                verbose_name="URL продукта",
            ),
        ),
    ]
